// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQGgzOq-y_awt0sa95wXyzcRZ1ZVMv-Cc',
    appId: '1:301767101320:web:f8d4b036b4c1e5a27fc83d',
    messagingSenderId: '301767101320',
    projectId: 'latihan-f45e3',
    authDomain: 'latihan-f45e3.firebaseapp.com',
    storageBucket: 'latihan-f45e3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3F2T7V3qsnK6lFHAcejRkk9k5j2nofOM',
    appId: '1:301767101320:android:4bd335cb43337f8a7fc83d',
    messagingSenderId: '301767101320',
    projectId: 'latihan-f45e3',
    storageBucket: 'latihan-f45e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJu_wgFfwkD009qM4MU_SVxUnk_bI-fqQ',
    appId: '1:301767101320:ios:dffac321894aa0f37fc83d',
    messagingSenderId: '301767101320',
    projectId: 'latihan-f45e3',
    storageBucket: 'latihan-f45e3.appspot.com',
    iosBundleId: 'com.example.flutterLoginExercise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJu_wgFfwkD009qM4MU_SVxUnk_bI-fqQ',
    appId: '1:301767101320:ios:1033605d90c05e607fc83d',
    messagingSenderId: '301767101320',
    projectId: 'latihan-f45e3',
    storageBucket: 'latihan-f45e3.appspot.com',
    iosBundleId: 'com.example.flutterLoginExercise.RunnerTests',
  );
}
